<?php

/**
 * @file
 * Contains hook implementations and global functions.
 */

/**
 * The URL path to receive IPN requests at.
 */
define('MYNAMEISBART_PAYPAL_IPN_LISTENER_PATH', 'mynameisbart_paypal_ipn');

/**
 * Implements hook_menu().
 */
function mynameisbart_paypal_ipn_menu() {
  $items[MYNAMEISBART_PAYPAL_IPN_LISTENER_PATH] = array(
    'load arguments' => array('payment_method'),
    'page callback' => 'mynameisbart_paypal_ipn_post',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Processes an IPN request based on POST data.
 */
function mynameisbart_paypal_ipn_post() {
  $ipn_variables = $_POST;
  foreach ($_POST as $ipn_variable => $value) {
    $ipn_variables[$ipn_variable] = urldecode($value);
  }
  if (MyNameIsBartPayPalIPNController::acknowledge($ipn_variables) && MyNameIsBartPayPalIPNController::validate($ipn_variables)) {
    $ipn = new MyNameIsBartPayPalIPN($ipn_variables);
    MyNameIsBartPayPalIPNController::save($ipn);
    MyNameIsBartPayPalIPNController::process($ipn_variables);
  }
}
